export const cityOptions = [
    {text: 'Deçan', value: 'Deçan'},
    {text: 'Dragash', value: 'Dragash'},
    {text: 'Ferizaj', value: 'Ferizaj'},
    {text: 'Fushë Kosovë', value: 'Fushë Kosovë'},
    {text: 'Gjakovë', value: 'Gjakovë'},
    {text: 'Gjilan', value: 'Gjilan'},
    {text: 'Gllogoc', value: 'Gllogoc'},
    {text: 'Graçanicë', value: 'Graçanicë'},
    {text: 'Hani i Elezit', value: 'Hani i Elezit'},
    {text: 'Istog', value: 'Istog'},
    {text: 'Junik', value: 'Junik'},
    {text: 'Kamenicë', value: 'Kamenicë'},
    {text: 'Kaçanik', value: 'Kaçanik'},
    {text: 'Klinë', value: 'Klinë'},
    {text: 'Kllokot', value: 'Kllokot'},
    {text: 'Leposaviq', value: 'Leposaviq'},
    {text: 'Lipjan', value: 'Lipjan'},
    {text: 'Malishevë', value: 'Malishevë'},
    {text: 'Mamushë', value: 'Mamushë'},
    {text: 'Mitrovicë (Jugu)', value: 'Mitrovicë (Jugu)'},
    {text: 'Mitrovicë (Veriu)', value: 'Mitrovicë (Veriu)'},
    {text: 'Novobërdë', value: 'Novobërdë'},
    {text: 'Obiliq', value: 'Obiliq'},
    {text: 'Partesh', value: 'Partesh'},
    {text: 'Pejë', value: 'Pejë'},
    {text: 'Podujevë', value: 'Podujevë'},
    {text: 'Prishtinë', value: 'Prishtinë'},
    {text: 'Prizren', value: 'Prizren'},
    {text: 'Rahovec', value: 'Rahovec'},
    {text: 'Ranillug', value: 'Ranillug'},
    {text: 'Shtime', value: 'Shtime'},
    {text: 'Shtërpcë', value: 'Shtërpcë'},
    {text: 'Skënderaj', value: 'Skënderaj'},
    {text: 'Suharekë', value: 'Suharekë'},
    {text: 'Viti', value: 'Viti'},   
    {text: 'Vushtrri', value: 'Vushtrri'},   
    {text: 'Zubin Potok', value: 'Zubin Potok'},
    {text: 'Zveçan', value: 'Zveçan'}
]